name: Auto update n8n
on:
  schedule:
    - cron: '7 4 * * 0'
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}
  
jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get n8n latest version
        id: n8n
        run: |
          version=$(gh api repos/n8n-io/n8n/releases/latest -q .tag_name)
          echo version=${version#n8n@} >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Update n8n version
        run: sed -i -E "s|(n8nio/n8n:)([0-9]+\\.[0-9]+\\.[0-9]+)|\1$version|" fly.toml
        env:
          version: ${{ steps.n8n.outputs.version }}
          
      - name: Add and commit fly.toml
        uses: EndBug/add-and-commit@v9
        with:
          add: fly.toml
          default_author: github_actions
          message: 'chore: Update n8n to ${{ steps.n8n.outputs.version }}'